name: Build RetroED

on: workflow_dispatch

jobs:
  win-build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Install Qt
      # You may pin to the exact commit or the version.
      # uses: jurplel/install-qt-action@c04feedfdfd6dbe64db62deda57fb0971a1bf440
      uses: jurplel/install-qt-action@v2.14.0
    - name: Run versiongen
      working-directory: RetroEDv2
      run: |
        py -m pip install pytz
        py versiongen.py $GITHUB_SHA
        mkdir ../build
    - name: Build RetroED
      working-directory: build
      run: |
        qmake ../RetroEDv2/RetroEDv2.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
        jom qmake_all
        jom Makefile.release
        jom -f Makefile.release
        
